[package]
name = "sr25519crust"
version = "0.1.0"
authors = ["Bogdan Vaneev <warchantua@gmail.com>"]
edition = "2018"

[lib]
name = "sr25519crust"
# probably we need to add dylib/lib/dll for mac/linux/windows
crate-type = ["cdylib", "staticlib"]

[dependencies]
schnorrkel = { version="0.1.1", features = ["nightly"] }

[dev-dependencies]
hex-literal = "0.1.4"
rand = "0.6.5"

[build-dependencies]
cbindgen = "0.8.5"
