[package]
name = "sr25519crust"
version = "0.1.0"
authors = ["Bogdan Vaneev <warchantua@gmail.com>"]
edition = "2018"

[lib]
name = "sr25519crust"
crate-type = ["dylib", "lib", "staticlib"]

[dependencies]
schnorrkel = "0.1.1"
hex = "0.3.2"
rand = "0.6.5"
hex-literal = "0.2.0"

[build-dependencies]
cbindgen = "0.8.5"
